site_name: GaiaFlow - MLOps tool streamlining Earth Observation ML projects.
repo_url: https://github.com/bcdev/gaiaflow
repo_name: bc-dev/gaiaflow

copyright: Copyright &copy; 2025 Brockmann Consult

nav:
  - Overview: index.md
  - Getting Started: getting_started.md
  - User guide - Dev: dev.md
  - User guide - Prod and Prod_local: prod.md
  - Tutorial: tutorial.md


theme:
  name: material
  # favicon: assets/logo-small.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bcdev/gaiaflow

plugins:
  - search
  - mkdocs-jupyter
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_toc_entry: true
            show_root_heading: true
            show_source: true
            heading_level: 2
            annotations_path: brief
            members_order: source