name: Package and Publish to PyPi

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  Python-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - name: checkout
        uses: actions/checkout@v4
      {% raw %}
      - name: Set up MicroMamba and install dependencies with Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python-version }}
      {% endraw %}
      - name: Lint with ruff
        run: |
          ruff check

      - name: Run unit tests
        shell: bash -l {0}
        run:
          pytest test/ --cov=xcube_gedidb --cov-report=xml

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          pytest -m "not gaiaflow" --cov={{ cookiecutter.package_name }} --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          verbose: true
          {% raw %}
          token: ${{ secrets.CODECOV_TOKEN }}
          {% endraw %}

  PyPi-Deploy:
    name: Publish {{ cookiecutter.package_name }} Package to PyPI
    runs-on: ubuntu-latest
    needs: python-tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          {% raw %}
          password: ${{ secrets.PYPI_API_TOKEN }}
          {% endraw %}
          verbose: true